using System.Globalization;
using System.Text;
using Modelry.Core.Model;

namespace Modelry.Core.CodeGen;

/// <summary>A generated file: path inside the zip and its text.</summary>
public sealed record GeneratedFile(string Path, string Content);

/// <summary>
/// Writes a <see cref="ModelPlan"/> as DXA .NET 2.x view models (C# 7.3, .NET Framework 4.6.2+):
/// one partial class per file with explicit semantic mapping, a vocabulary constants class and one area registration per area.
/// </summary>
public static class DxaCSharpWriter
{
    public const string VocabularyClass = "SemanticVocabulary";
    public const string CoreVocabulary = "http://www.sdl.com/web/schemas/core";

    public static List<GeneratedFile> Write(ModelPlan plan)
    {
        var files = new List<GeneratedFile> { new("Models/" + VocabularyClass + ".cs", Vocabulary(plan)) };
        files.AddRange(plan.Classes.Select(c => new GeneratedFile(c.FilePath, Class(plan, c))));
        foreach (var area in plan.Areas)
            files.Add(new GeneratedFile($"Areas/{area}/{area}AreaRegistration.cs", Registration(plan, area)));
        return files;
    }

    public static string RegistrationNamespace(ModelPlan plan)
    {
        var ns = plan.Options.RootNamespace;
        return ns.EndsWith(".Models", StringComparison.Ordinal) ? ns[..^".Models".Length] : ns;
    }

    public static string TypeName(ModelProperty p)
    {
        var t = p.Kind switch
        {
            ModelValueKind.RichText => "RichText",
            ModelValueKind.Number => "double",
            ModelValueKind.Date => p.IsList ? "DateTime" : "DateTime?",
            ModelValueKind.Link => "Link",
            ModelValueKind.Tag => "Tag",
            ModelValueKind.Model => p.ModelName!,
            ModelValueKind.AnyEntity => "EntityModel",
            ModelValueKind.AnyMedia => "MediaItem",
            _ => "string"
        };
        return p.IsList ? $"List<{t}>" : t;
    }

    private static string Header(ModelPlan plan, string what)
    {
        var o = plan.Options;
        return $"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     Generated by Modelry from '{Comment(o.SourceFileName)}' on {o.GeneratedUtc.ToString("d MMM yyyy, HH:mm", CultureInfo.InvariantCulture)} UTC.
            //     {Comment(what)}
            //     Changes to this file are lost when the models are generated again.
            //     Add behaviour in a separate file: every class is partial.
            // </auto-generated>
            //------------------------------------------------------------------------------

            """;
    }

    private static string Vocabulary(ModelPlan plan)
    {
        var sb = new StringBuilder(Header(plan, "Semantic vocabulary used by every generated model."));
        sb.Append($$"""
            namespace {{plan.Options.RootNamespace}}
            {
                /// <summary>
                /// Semantic mapping constants. DXA publishes every schema in the core vocabulary with its XML root element
                /// name as the entity name, so each model declares that entity explicitly; this also covers embedded schemas,
                /// which have no namespace. The prefix "{{plan.SemanticPrefix}}" is local to the models and avoids clashing with
                /// the "s" (schema.org) prefix that DXA base classes such as Image and Download declare.
                /// </summary>
                internal static class {{VocabularyClass}}
                {
                    public const string Core = "{{CoreVocabulary}}";
                    public const string Prefix = "{{plan.SemanticPrefix}}";
                }
            }

            """);
        return sb.ToString();
    }

    private static string Class(ModelPlan plan, ModelClass c)
    {
        var s = c.Schema;
        var root = s.RootElementName ?? c.Name;
        var usesList = c.Properties.Any(p => p.IsList);
        var views = plan.Registrations.Where(r => r.ModelType == c.Name).Select(r => $"{r.Area}:{r.View}").Distinct().ToList();

        var sb = new StringBuilder(Header(plan, $"Schema '{s.Title}' ({s.Purpose}{(s.RelativePath is "." ? "" : ", " + s.RelativePath)})."));
        sb.AppendLine("using System;");
        if (usesList) sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Sdl.Web.Common.Models;");
        sb.AppendLine();
        sb.AppendLine($"namespace {plan.Options.RootNamespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        foreach (var line in Wrap(s.Description ?? $"{s.Title} ({s.Purpose} schema).")) sb.AppendLine($"    /// {Xml(line)}");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <remarks>");
        sb.AppendLine($"    /// Schema: {Xml(s.Title)} ({s.Purpose}), XML root element <c>{Xml(root)}</c>.");
        sb.AppendLine(views.Count > 0
            ? $"    /// Views: {Xml(string.Join(", ", views))}."
            : c.Kind == ModelKind.Entity && plan.ModelOnlyRegistrations.Contains(c.Name)
                ? "    /// No view of its own: registered without a view so lists and links can resolve it."
                : $"    /// {KindNote(c)}");
        sb.AppendLine("    /// </remarks>");
        sb.AppendLine("    [Serializable]");
        sb.AppendLine($"    [SemanticEntity(Vocab = {VocabularyClass}.Core, EntityName = \"{root}\", Prefix = {VocabularyClass}.Prefix)]");
        sb.AppendLine($"    public partial class {c.Name} : {c.BaseType}");
        sb.AppendLine("    {");

        var members = new List<string>();
        if (c.Kind == ModelKind.Page)
            members.Add($"        /// <summary>Creates the page model; DXA passes the page ID.</summary>\n        public {c.Name}(string id) : base(id)\n        {{\n        }}");
        if (c.Kind == ModelKind.Region)
            members.Add($"        /// <summary>Creates the region model; DXA passes the region name.</summary>\n        public {c.Name}(string name) : base(name)\n        {{\n        }}");

        foreach (var p in c.Properties)
        {
            var f = p.Field;
            var m = new StringBuilder();
            m.AppendLine($"        /// <summary>{Xml(Sentence(f.Label))}</summary>");
            var remarks = Remarks(p);
            if (remarks.Length > 0)
            {
                m.AppendLine("        /// <remarks>");
                foreach (var line in Wrap(remarks)) m.AppendLine($"        /// {Xml(line)}");
                m.AppendLine("        /// </remarks>");
            }
            m.AppendLine($"        [SemanticProperty(\"{plan.SemanticPrefix}:{f.XmlName}\")]");
            m.Append($"        public {TypeName(p)} {p.Name} {{ get; set; }}");
            if (p.BooleanHelperName is not null)
            {
                m.AppendLine();
                m.AppendLine();
                m.AppendLine($"        /// <summary>True when '{Xml(f.Label)}' is checked (<see cref=\"{p.Name}\"/> is \"{Xml(p.CheckedValue!)}\").</summary>");
                m.AppendLine("        [SemanticProperty(IgnoreMapping = true)]");
                m.Append($"        public bool {p.BooleanHelperName} => string.Equals({p.Name}, \"{Escape(p.CheckedValue!)}\", StringComparison.OrdinalIgnoreCase);");
            }
            members.Add(m.ToString());
        }
        sb.AppendLine(string.Join(Environment.NewLine + Environment.NewLine, members.Select(x => x.TrimEnd())));
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString().Replace("\r\n", "\n");
    }

    private static string Registration(ModelPlan plan, string area)
    {
        var regs = plan.Registrations.Where(r => string.Equals(r.Area, area, StringComparison.OrdinalIgnoreCase)).ToList();
        var isDefault = string.Equals(area, plan.Options.DefaultArea, StringComparison.OrdinalIgnoreCase);
        var kindOf = plan.Classes.ToDictionary(c => c.Name, c => c.Kind);
        string Group(ViewRegistration r) => r.ModelType == "PageModel" || kindOf.TryGetValue(r.ModelType, out var k) && k == ModelKind.Page ? "Page views (Page Templates)"
            : r.ModelType == "RegionModel" || kindOf.TryGetValue(r.ModelType, out var k2) && k2 == ModelKind.Region ? "Region views"
            : "Entity views (Component Templates)";

        var body = new StringBuilder();
        foreach (var g in regs.GroupBy(Group).OrderBy(g => g.Key.StartsWith("Entity") ? 0 : g.Key.StartsWith("Page") ? 1 : 2))
        {
            if (body.Length > 0) body.AppendLine();
            body.AppendLine($"            // {g.Key}");
            foreach (var r in g.OrderBy(r => r.View, StringComparer.Ordinal))
            {
                var ctrl = r.Controller is null ? "" : $", \"{r.Controller}\"";
                body.AppendLine($"            RegisterViewModel(\"{r.View}\", typeof({r.ModelType}){ctrl}); // {Comment(r.Source)}");
            }
        }
        if (isDefault && plan.ModelOnlyRegistrations.Count > 0)
        {
            if (body.Length > 0) body.AppendLine();
            body.AppendLine("            // Models without a view of their own: registered so DXA can resolve them from their schema");
            body.AppendLine("            // (list items, Component Links typed as EntityModel).");
            foreach (var m in plan.ModelOnlyRegistrations) body.AppendLine($"            RegisterViewModel(typeof({m}));");
        }
        if (body.Length == 0) body.AppendLine("            // The workbook lists no views for this area.");

        var sb = new StringBuilder(Header(plan, $"View model registration for the '{area}' area."));
        sb.Append($$"""
            using Sdl.Web.Common.Models;
            using Sdl.Web.Mvc.Configuration;
            using {{plan.Options.RootNamespace}};

            namespace {{RegistrationNamespace(plan)}}
            {
                /// <summary>
                /// Registers the {{area}} area's DXA views with their view models. One view name maps to one model type;
                /// several views may share a model. The controller is given only where the Component Template sets one
                /// (otherwise DXA uses Entity, Region or Page from the model type).
                /// </summary>
                public class {{area}}AreaRegistration : BaseAreaRegistration
                {
                    /// <inheritdoc />
                    public override string AreaName => "{{area}}";

                    /// <inheritdoc />
                    protected override void RegisterAllViewModels()
                    {
            {{body.ToString().TrimEnd()}}
                    }
                }
            }

            """);
        return sb.ToString().Replace("\r\n", "\n");
    }

    private static string KindNote(ModelClass c) => c.Kind switch
    {
        ModelKind.Embedded => "Embedded schema: used as the type of fields that embed it.",
        ModelKind.Media => "Multimedia schema: used as the type of Multimedia Links that target it.",
        ModelKind.Keyword => "Keyword metadata schema: used as the type of keyword fields whose category has this metadata.",
        ModelKind.Page => "Page model: registered for the Page Template views below in the area registration.",
        _ => "Region model."
    };

    private static string Remarks(ModelProperty p)
    {
        var f = p.Field;
        var parts = new List<string>();
        var type = IaVocabulary.FieldTypeNames[f.Type];
        if (f.Type == IaFieldType.EmbeddedSchema && f.EmbeddedSchema is not null) type += $" ({f.EmbeddedSchema})";
        if (f.Type is IaFieldType.ComponentLink or IaFieldType.MultimediaLink && f.AllowedTargetSchemas.Count > 0)
            type += $" to {string.Join(", ", f.AllowedTargetSchemas)}";
        if (f.Type == IaFieldType.Keyword && f.Category is not null) type += $" from category {f.Category}";
        var occurs = f.MaxOccurs == 1 ? "" : f.MaxOccurs < 0 ? ", multi-value" : $", up to {f.MaxOccurs} values";
        parts.Add($"{type}{occurs}{(f.Mandatory ? ", mandatory" : "")}{(f.Section == IaFieldSection.Metadata ? ", metadata section" : "")}; field '{f.XmlName}'.");
        if (f.ListValues.Count > 0 && f.Type == IaFieldType.Text) parts.Add($"Values: {string.Join(", ", f.ListValues)}.");
        if (f.Type == IaFieldType.Number && !f.Mandatory) parts.Add("0 when empty.");
        if (!string.IsNullOrWhiteSpace(f.HelpText)) parts.Add(Sentence(f.HelpText!));
        return string.Join(" ", parts);
    }

    private static string Sentence(string text)
    {
        var t = text.Trim();
        return t.Length == 0 || t.EndsWith('.') || t.EndsWith('?') || t.EndsWith('!') || t.EndsWith(')') ? t : t + ".";
    }

    private static IEnumerable<string> Wrap(string text, int width = 110)
    {
        foreach (var para in text.Replace("\r", "").Split('\n', StringSplitOptions.RemoveEmptyEntries))
        {
            var line = new StringBuilder();
            foreach (var word in para.Split(' ', StringSplitOptions.RemoveEmptyEntries))
            {
                if (line.Length > 0 && line.Length + word.Length + 1 > width) { yield return line.ToString(); line.Clear(); }
                if (line.Length > 0) line.Append(' ');
                line.Append(word);
            }
            if (line.Length > 0) yield return line.ToString();
        }
    }

    private static string Xml(string text) => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    private static string Comment(string text) => text.Replace("\r", " ").Replace("\n", " ");
    private static string Escape(string text) => text.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
