using System.Globalization;
using System.IO.Compression;
using System.Text;
using Modelry.Core.Model;

namespace Modelry.Core.CodeGen;

public sealed record ModelPackageResult(byte[] Zip, string FileName, int Classes, int Registrations, int Files);

/// <summary>Packs the generated C# files with a README and a schema-to-class map (CSV) into one zip.</summary>
public static class ModelPackage
{
    public const string Target = "DXA .NET 2.3 (Tridion Sites 10.1), C# 7.3, .NET Framework 4.6.2 or later";

    public static ModelPackageResult Build(ModelPlan plan)
    {
        var files = DxaCSharpWriter.Write(plan);
        files.Add(new GeneratedFile("ModelMap.csv", Map(plan)));
        files.Add(new GeneratedFile("README.md", Readme(plan, files)));

        using var ms = new MemoryStream();
        using (var zip = new ZipArchive(ms, ZipArchiveMode.Create, leaveOpen: true))
        {
            foreach (var f in files.OrderBy(f => f.Path, StringComparer.Ordinal))
            {
                var entry = zip.CreateEntry(f.Path, CompressionLevel.Optimal);
                entry.LastWriteTime = plan.Options.GeneratedUtc;
                using var w = new StreamWriter(entry.Open(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
                w.Write(f.Content.Replace("\r\n", "\n").Replace("\n", "\r\n")); // CRLF: Visual Studio / .NET Framework solutions
            }
        }
        var area = plan.Options.DefaultArea ?? "Site";
        return new ModelPackageResult(ms.ToArray(), $"{area}_DXA_Models_{plan.Options.GeneratedUtc:yyyyMMdd_HHmm}.zip",
            plan.Classes.Count, plan.Registrations.Count + plan.ModelOnlyRegistrations.Count, files.Count);
    }

    /// <summary>One row per schema: what it became, where, and which views use it.</summary>
    public static string Map(ModelPlan plan)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Csv("Schema", "Purpose", "Model class", "Base type", "File", "Properties", "Registered views", "Notes"));
        foreach (var c in plan.Classes.OrderBy(c => c.Schema.Row))
        {
            var views = plan.Registrations.Where(r => r.ModelType == c.Name).Select(r => $"{r.Area}:{r.View}{(r.Controller is null ? "" : $" ({r.Controller})")}");
            var note = plan.ModelOnlyRegistrations.Contains(c.Name) ? "Registered without a view" : "";
            sb.AppendLine(Csv(c.Schema.Title, c.Schema.Purpose.ToString(), $"{plan.Options.RootNamespace}.{c.Name}", c.BaseType, c.FilePath,
                c.Properties.Count.ToString(CultureInfo.InvariantCulture), string.Join("; ", views), note));
        }
        foreach (var s in plan.Skipped.OrderBy(s => s.Schema.Row))
            sb.AppendLine(Csv(s.Schema.Title, s.Schema.Purpose.ToString(), "", "", "", "", "", "No class: " + s.Reason));
        foreach (var r in plan.Registrations.Where(r => r.ModelType is "PageModel" or "RegionModel"))
            sb.AppendLine(Csv("(" + r.Source + ")", "View", r.ModelType, "", "", "", $"{r.Area}:{r.View}", "DXA built-in model"));
        return sb.ToString();
    }

    private static string Readme(ModelPlan plan, List<GeneratedFile> files)
    {
        var o = plan.Options;
        var regNs = DxaCSharpWriter.RegistrationNamespace(plan);
        var sb = new StringBuilder();
        sb.AppendLine($"# DXA view models – {o.DefaultArea}");
        sb.AppendLine();
        sb.AppendLine($"Generated by Modelry from `{o.SourceFileName}` on {o.GeneratedUtc.ToString("d MMM yyyy, HH:mm", CultureInfo.InvariantCulture)} UTC.");
        sb.AppendLine($"Target: {Target}.");
        sb.AppendLine();
        sb.AppendLine($"{plan.Classes.Count} model classes in namespace `{o.RootNamespace}`, " +
                      $"{plan.Registrations.Count} view registrations and {plan.ModelOnlyRegistrations.Count} registrations without a view in `{regNs}`.");
        sb.AppendLine();
        sb.AppendLine("## What is in the zip");
        sb.AppendLine();
        sb.AppendLine("| Folder | Contents |");
        sb.AppendLine("| --- | --- |");
        foreach (var g in plan.Classes.GroupBy(c => c.Folder).OrderBy(g => g.Key))
            sb.AppendLine($"| `{g.Key}` | {g.Count()} {Describe(g.First().Kind)} |");
        sb.AppendLine($"| `Models/{DxaCSharpWriter.VocabularyClass}.cs` | Semantic vocabulary and prefix constants |");
        foreach (var a in plan.Areas) sb.AppendLine($"| `Areas/{a}/{a}AreaRegistration.cs` | `RegisterViewModel` calls for the {a} area |");
        sb.AppendLine("| `ModelMap.csv` | Every schema: its class, base type, file and registered views, or why it has no class |");
        sb.AppendLine();
        sb.AppendLine("## Add them to your DXA module");
        sb.AppendLine();
        sb.AppendLine("1. Copy `Models/` and `Areas/` into the module project (a class library referencing the DXA framework packages, e.g. `Sdl.Dxa.Framework.Web8`, which provide `Sdl.Web.Common` and `Sdl.Web.Mvc`).");
        sb.AppendLine($"2. Put the Razor views under `Areas/{o.DefaultArea}/Views/Entity`, `Views/Page` and `Views/Region` (and `Views/<Controller>` for templates with their own controller), named exactly as registered.");
        sb.AppendLine("3. Build. Every class is `partial`: put hand-written members in a second file (for example `HeroBanner.Custom.cs`) so a regenerated file can simply replace the old one.");
        sb.AppendLine("4. Publish the Publication Settings page so DXA has the current semantic schema mapping, then publish a test page per Page Template.");
        sb.AppendLine();
        sb.AppendLine("## How fields are mapped");
        sb.AppendLine();
        sb.AppendLine($"Each class declares `[SemanticEntity(Vocab = core, EntityName = <XML root element>, Prefix = \"{plan.SemanticPrefix}\")]` and each property `[SemanticProperty(\"{plan.SemanticPrefix}:<xml name>\")]`. " +
                      "DXA publishes every schema in the core vocabulary with its root element name, so this matches without semantic annotations in the CMS and also works for embedded schemas, which have no namespace. " +
                      $"The prefix `{plan.SemanticPrefix}` differs from the `s` prefix that DXA's own Image and Download classes use, so inherited mappings do not collide.");
        sb.AppendLine();
        sb.AppendLine("| Field type | C# type |");
        sb.AppendLine("| --- | --- |");
        sb.AppendLine("| Text, Multi-line Text, External Link | `string` |");
        sb.AppendLine("| Text with a single-value checkbox (\"Yes\") | `string` (mapped, named `…Text`) plus a read-only `bool` for views |");
        sb.AppendLine("| Rich Text | `RichText` |");
        sb.AppendLine("| Number | `double` (0 when empty) |");
        sb.AppendLine("| Date | `DateTime?` |");
        sb.AppendLine("| Embedded Schema | the embedded schema's class |");
        sb.AppendLine("| Component Link to one schema | that schema's class (DXA builds the linked component) |");
        sb.AppendLine("| Component Link to several schemas | `EntityModel` (DXA picks the registered class from the linked component's schema) |");
        sb.AppendLine("| Component Link without target schemas | `Link` (resolved URL) |");
        sb.AppendLine("| Multimedia Link | the multimedia schema's class, or `MediaItem` |");
        sb.AppendLine("| Keyword | the category's keyword metadata class, or `Tag` |");
        sb.AppendLine("| Any field with more than one value | `List<T>` (null when the field is empty) |");
        sb.AppendLine();
        sb.AppendLine("Multimedia schemas that allow only image types derive from DXA's `Image`; the others derive from `Download`, which already renders a link (`ToHtml`). Page models take the page ID in their constructor and region models the region name, as DXA creates them that way.");
        sb.AppendLine();
        sb.AppendLine("## Check before relying on it");
        sb.AppendLine();
        sb.AppendLine("This code was generated, not compiled against your DXA solution or run against the CMS. Check these on the first build and publish:");
        sb.AppendLine();
        sb.AppendLine("- `BaseAreaRegistration.RegisterViewModel(Type)` (registration without a view) exists in your DXA version; on older versions register those models with a dummy view or remove the calls if nothing links to them as `EntityModel`.");
        sb.AppendLine("- Keyword fields typed with a keyword metadata class get their metadata properties only if the keyword's metadata is in the published data model; if they come back empty, change those properties to `Tag` or read the metadata in a controller.");
        sb.AppendLine("- Component Links typed with a specific class need enough link expansion depth (the project notes recommend 2–3) or the linked entity is not built.");
        sb.AppendLine("- Page and region model constructors (`(string id)`, `(string name)`) match your DXA version.");
        sb.AppendLine("- Templates with a Controller (for example `List`, `Navigation`) are registered with that controller name; the controller's model expectations (such as DXA's list controller) still need a developer's review.");
        var findings = plan.Issues.OrderBy(i => i.Level).ToList();
        if (findings.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("## Findings from generation");
            sb.AppendLine();
            sb.AppendLine("| Level | Item | What to know |");
            sb.AppendLine("| --- | --- | --- |");
            foreach (var i in findings) sb.AppendLine($"| {i.Level} | {Md(i.Item)} | {Md(i.Message)} |");
        }
        if (plan.Skipped.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("## Schemas without a class");
            sb.AppendLine();
            foreach (var s in plan.Skipped) sb.AppendLine($"- **{Md(s.Schema.Title)}** – {Md(s.Reason)}");
        }
        sb.AppendLine();
        sb.AppendLine($"Files: {files.Count + 1}.");
        return sb.ToString();
    }

    private static string Describe(ModelKind kind) => kind switch
    {
        ModelKind.Entity => "component models (`EntityModel`)",
        ModelKind.Embedded => "embedded schema models (`EntityModel`)",
        ModelKind.Media => "multimedia models (`Image` / `Download`)",
        ModelKind.Keyword => "keyword models (`KeywordModel`)",
        ModelKind.Page => "page models (`PageModel`)",
        _ => "region models (`RegionModel`)"
    };

    private static string Md(string s) => s.Replace("|", "\\|").Replace("\n", " ");

    private static string Csv(params string[] values) =>
        string.Join(",", values.Select(v => v.IndexOfAny(new[] { ',', '"', '\n', ';' }) >= 0 ? "\"" + v.Replace("\"", "\"\"") + "\"" : v));
}
